### ISSUE TITLE
https://github.com/hnesk/browse-ocrd/tree/diff-view does not available

### ISSUE THREAD

**Issue by Aysoltan** [kba/vdhd-2021-05-12#1]
Hey, is there any possibility to merge diff view in browse-ocrd tool in order to view evaluation results? Best, Aysoltan

**Comment by kba** [comment]
This branch was [merged](https://github.com/hnesk/browse-ocrd/commit/ce0f51564806ef78e679d1b0319eebb00b23de19) a few weeks back, diff view is available in the `master` branch now.

**Comment by Aysoltan** [comment]
Thanks so much for your reply! Would there be some way to get guidance on how that add-on could be integrated into browse-ocrd? How did you do that?

**Comment by kba** [comment]
After installing browse-ocrd, open a new view (buttons on the top-right), choose "Text-Diff", select file groups you want to compare.

**Comment by Aysoltan** [comment]
Many Thanks for your suggestion. I've already seen this option in your Demo. But there is no "Text-Diff" option in my browse-orcd tool. That was the reason I asked you. I thought maybe there is some special way to integrate this branch into the tool. Kindly. Aysoltan

**Comment by kba** [comment]
Have you updated the tool? Currently, it's best to install from the github repo:

```
git clone https://github.com/hnesk/browse-ocrd
cd browse-ocrd
# activate your venv if not activated already
source /path/to/venv/bin/activate
pip install .
```

I highly recommend upgrading because since a few days ago, there is built-in support for visual display of regions, lines etc., so no need to set up external PAGEViewer.

These changes will be discussed in [today's Open Tech Call at 2pm](https://ocr-d.de/en/community), feel free to join to learn more.
